alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -alF'
alias grep='grep --color=auto'
alias gs='git status'
alias gl='git log'
alias gaa='git add .'
alias gcan='git commit --amend --no-edit'
alias ebrc='vim ~/.bashrc'
alias rbrc='source ~/.bashrc'
alias eba='vim ~/.bash_aliases'
alias evrc='vim ~/.config/nvim/init.lua'
alias dotfiles='/usr/bin/git --git-dir="$HOME/.dotfiles/" --work-tree="$HOME"'
